// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdl4FFLkvm87c6OhWlgnzkV_bw39uplAQ',
    appId: '1:293128196245:web:97d2b4e9ef481395e80b9c',
    messagingSenderId: '293128196245',
    projectId: 'dilemma-7b7a5',
    authDomain: 'dilemma-7b7a5.firebaseapp.com',
    storageBucket: 'dilemma-7b7a5.appspot.com',
    measurementId: 'G-WL2PXBY153',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMrO6M0RJHzYC69nb7YqjwC0FTo_5DjYw',
    appId: '1:293128196245:android:c6fdc1cc3a10d321e80b9c',
    messagingSenderId: '293128196245',
    projectId: 'dilemma-7b7a5',
    storageBucket: 'dilemma-7b7a5.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdl4FFLkvm87c6OhWlgnzkV_bw39uplAQ',
    appId: '1:293128196245:web:d1d7d68b42313849e80b9c',
    messagingSenderId: '293128196245',
    projectId: 'dilemma-7b7a5',
    authDomain: 'dilemma-7b7a5.firebaseapp.com',
    storageBucket: 'dilemma-7b7a5.appspot.com',
    measurementId: 'G-QW0VFD4Q43',
  );
}
